In [2]:
import numpy as np
arr = np.zeros ((3,3), dtype = int )
print (arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
one = np.ones((3,3),dtype=float)
print (one) # you will see .(dot) because of float

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
mylist  = [1,2,3,4,5,6,7,8,9]
print ('type of mylist',type(mylist))
npArray = np.asarray(mylist)
print ('type of mylist',type(npArray))
print (npArray)

type of mylist <class 'list'>
type of mylist <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [24]:
mylist = [1,2,3,4]
arr = np.asarray(mylist , dtype = float , order = 'F' )
print (arr)

[1. 2. 3. 4.]
