In [3]:
import numpy as np 
arr = np.arange(8)
print ('first stage array :',arr)
print ('dimension of arr :',arr.ndim)

first stage array : [0 1 2 3 4 5 6 7]
dimension of arr : 1


In [5]:
import numpy as np
arr = np.arange(8)
arr2d = arr.reshape(2,4)
print (arr2d)
print ('dimension of arr2d :',arr2d.ndim)
#1 + 1 depth = (3dimension)

[[0 1 2 3]
 [4 5 6 7]]
dimension of arr2d : 2


In [8]:
import numpy as np
arr = np.arange(8)
arr3d = arr.reshape(2,2,2) #last 2 is 2 depth
print (arr3d)
print ('dim of arr3d :',arr3d.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
dim of arr3d : 3


In [13]:
import numpy as np
arr = np.arange (10)
arr2d = arr.reshape(2,5)
print (arr2d)
print ('dim of arr2d is :',arr2d.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]]
dim of arr2d is : 2
