In [2]:
import numpy as np
dlist = [1,2,3,4]

arr = np.fromiter(dlist , dtype = int)
print (arr)
print (type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# arange incremental sequence

In [3]:
arrobj = np.arange(1,20,2)
print (arrobj)
print (type(arrobj))

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>


# linspace incremental sequence non-integer

In [34]:
arrobj = np.linspace (0 ,20 ,3) #count
print (arrobj)

[ 0. 10. 20.]


In [6]:
arrobj = np.linspace (0 ,20 ,12) #count
arr = arrobj.reshape(2,3,2)
print (arrobj,'\n')
print (arr,'\n')
print (arr.ndim)

[ 0.          1.81818182  3.63636364  5.45454545  7.27272727  9.09090909
 10.90909091 12.72727273 14.54545455 16.36363636 18.18181818 20.        ] 

[[[ 0.          1.81818182]
  [ 3.63636364  5.45454545]
  [ 7.27272727  9.09090909]]

 [[10.90909091 12.72727273]
  [14.54545455 16.36363636]
  [18.18181818 20.        ]]] 

3
