# Logarithmic sequence

In [3]:
import numpy as np
arrObj = np.logspace(0,2,5) #10**0 10**2 ten power zero is equal to 1 
print (arrObj)

[  1.           3.16227766  10.          31.6227766  100.        ]


# Meshgrid Arrays

In [4]:
import numpy as np

x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2 ,3])
X, Y = np.meshgrid(x, y)
Z = (X+Y) ** 2

print(X, '\n')
print(Y, '\n')
print(Z, '\n')

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]
 [-1  0  1]] 

[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]
 [ 3  3  3]] 

[[ 9  4  1]
 [ 1  0  1]
 [ 1  4  9]
 [ 4  9 16]] 



# Properties of Array

In [7]:
import numpy as np 

x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X,Y = np.meshgrid(x,y)

def full(inarray):
    newarr = np.full_like(inarray,4)
    return newarr
full (X)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [2]:
import numpy as np

x = np.identity(4)
print(x)

print('\n')

y = np.eye(4,k=-1)#diogimal
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [3]:
import numpy as np
arr = np.arange(1, 20, 5)
diarry = np.diag(arr, k=-2)
print(diarry)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  0 11  0  0  0]
 [ 0  0  0 16  0  0]]


# Indexing and Slicing

In [8]:
import numpy as np

arr = np.arange (0,10)
print (arr)
print (arr[1 : -1])
print (arr[1 : -1 : 2]) #show second element, 1 second element is 3 ,and 3 element is 5 and etc ...
print (arr[::-5]) 

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]
[1 3 5 7]
[9 4]


# Flatten

In [34]:
import numpy as np

data = np.arange(8)
dim = data.reshape(2, 4)
print(dim)
flat = dim.flatten()
print(flat)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


In [35]:
row_vector = flat[np.newaxis, :]
print (row_vector)

[[0 1 2 3 4 5 6 7]]


In [32]:
colum_vector = flat[:, np.newaxis]
print(colum_vector)
colum_vector.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


(8, 1)

In [25]:
new_arr = row_vector + colum_vector
print(new_arr)

[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


# Vstack   Vs   Hstack

In [12]:
import numpy as np

arr = np.arange (5)
exp = np.expand_dims (arr , axis=1)
print (exp)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [13]:
row_exp = np.expand_dims (arr , axis=0)
print (row_exp)

[[0 1 2 3 4]]


In [6]:
vs = np.vstack ((arr ,arr ,arr))
print (vs)
hs = np.hstack ((arr , arr , arr))
print (hs)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
